In [1]:
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')
from bs4 import BeautifulSoup
import requests
import selenium
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import Select
import time
from datetime import datetime,date,timedelta
from gspread_pandas import Spread,Client
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import os

my_credentials={
  "type": "service_account",
  "project_id": "crafty-plateau-328717",
  "private_key_id": "4afdb5a0906054d2d69cd46b2e8af41b73b9b8a7",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcQv0qyESqHiYz\n82V5rSDiEG8xMGF0hIC9cJirwrDgAhEpjKIQRnJ227g6CP/8CTYYSrvJXmGzTZrB\n+FtrYWeZPjuIZGPyPJShIG//4LWcjlnh/h5zilKcmyaKsu5M0BSWiW0rkIUwYFgS\nox6xfiW3UbYWIUAGVvwDBYopUExaEV/a9l8p43pKDXHmZfq4ZIu2XgLDqalDLbCW\n1FjU7umMWS9KEvibo6mUkia9kkw1DvEsIkbWny3Bm0SoDLeqG0B6OsXhOYMfEJ+W\nSR80TR4Fu+EVfzRocwNVQHOKB2o0mbd/0AA1z/OPGM99QJXXKm8+CdV0KTbj6MUB\ns2/YTlG5AgMBAAECggEAKJ8IHrhBhZg61nDogYiu3FJIl2tDReBb99QIrACjaySm\ncqG3j8XWPVpnPvjC8QHn4pIB0PDhltZUmLpLbeHQX+AszYoqLpYCmTaowSl5hO5x\n4C5kAk37z1sDwCegsDTd3ydoJVUpYxMZmxJPSk+n+AePS8SFEMZBAvOmF9lxw1hC\nJoYkw4/H9XvuW7fTiOK2le6GokWgDUqSgTQRHO78NION1Z5pB5ymAKrV7w5GH4LI\nkFIuOxQEHhLv0a2URVEzkHX3VGPbBHF4MQ/Z8ObxqEsefkOnEpRIRTsE8+G44coB\nYbVdhe0132qgotEN1GvsBLwq+TJIknt38jkDcs9sKwKBgQD+sGqDtvCzSz5rk/Xg\nNHFOq9FsWSeUuw9jxw4XJxVqYbJbLcy0DmfIPg1rZgPW8X+6upt5RigHVBixqz74\nsnP9IvmVuoU6s9VoW1HaYbnbg5Zqp3WFa6xHZv/vXIapfCX8binEsVWwYW2gb2AJ\nE13jFJWZB7n8zatEk9ho1Rv50wKBgQDdZTXjsc0N3DZhCR39zPGr811VBmnXuUwW\nG1MG7z4npe2eFeTYHepKN8c3Ot+boyDm+K+NsEYHLH6wlcXFxMHAgSY6xAe8k+4i\n8EgwgUPfmawUrv7tXsAhASZNJwoE4S9S/kY/WFJR6CddaMUYvNtle5P99D//uoGG\nXcJWdEsiwwKBgQDBNaoIM98T1RAMYlmTdZVDfjrIPDY3sVSyd85rp/2qD2VToEH7\nkjYPBWv+voxJIjmouWm6rYsuTBDTr7p8xjwRm9fFS5NIfiZ2HVjSF3L8YS3ZySHx\nTkaKgEvGFOYfawwSHKxZB8KepLqajANJv0RpQTNfvSnN62RzCMmSdaDcewKBgQC8\nKuprdNHYRuL9BDe2X7rDr5sSydmpnPa7D0w455wHLLLRmsAeowZfQBsUqPgmGra7\nOIBUx44tSLcAtLscBMe8KshoR/ZfY8eRcHGasDMU11J3XeiTrOVU59o61sRgM1f6\njNz9t753mP3kGUjzZoh+L1MwE6lVW5n8rrGes0as6wKBgE54ZYZcUXRbOh+d1I9e\njWfwqr/mfvVGUZIBP4qDgL4dNHPWzWT7gjZIQUWJyXIMjP+04dly5ugJIX5UEC1M\nWPH1f9nsW3tvSp5suycEvtyXqEqrudLTHPOKhFWFDdh1bpO6y6GuAXMBU7FywTgi\n49Cl8Nil36anL8yJHhf7RSOF\n-----END PRIVATE KEY-----\n",
  "client_email": "aakashgooglesheets@crafty-plateau-328717.iam.gserviceaccount.com",
  "client_id": "108448941747378112883",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/aakashgooglesheets%40crafty-plateau-328717.iam.gserviceaccount.com"
}

In [26]:
spread = Spread('GIF_2025_Mapping_Requirement',config=my_credentials) ## worksheet_name
sheet = spread.open_sheet("Amazon_Sov")                                        ##sheet_name
asins_sheet = spread.sheet_to_df(sheet=sheet,index=0)
asins_sheet.head()

  category sub_category    BCG                   keyword account
0      MIW       Trunks  Brand     jockey under wear men  Jockey
1      MIW       Trunks  Brand   jokey underwear for men  Jockey
2      MIW       Trunks  Brand                    jockey  Jockey
3      MIW       Trunks  Brand          jockey underwear  Jockey
4      MIW       Trunks  Brand  jockey underwear for man  Jockey

In [7]:
keyword_list=asins_sheet['keyword'][0:20]

In [8]:
print(len(keyword_list))

20

In [ ]:
# keyword_list=keyword_list[:350]               # Rohit
# keyword_list=keyword_list[350:630]            # Ajay
# keyword_list=keyword_list[630:910]           # Koushik
# keyword_list=keyword_list[910:1190]          # Surya
# keyword_list=keyword_list[1350:1400]          # shruthi
# keyword_list=keyword_list[1470:1750]          # jibin
# keyword_list=keyword_list[1750:2030]          # karnakaran
# keyword_list=keyword_list[2030:2310]           # Hemanth
# keyword_list=keyword_list[2310:2590]           # sumit
# keyword_list=keyword_list[2590:2870]           # Harish
# keyword_list=keyword_list[2870:3150]           # Hari Prasad
# keyword_list=keyword_list[3150:3430]           # Rishab
# keyword_list=keyword_list[3430:]                # Rajshekhar

In [9]:
print(len(keyword_list))

20

In [10]:
keyword_list

0        jockey under wear men
1      jokey underwear for men
2                       jockey
3             jockey underwear
4     jockey underwear for man
5         jockey trunk for men
6     jockey underwear for men
7        mens underwear jockey
8      underwear for men combo
9      underwear for man combo
10           underwear for man
11              mens underwear
12           underwear for men
13               inner for men
14                   underwear
15          xyxx underwear men
16              trunks for man
17               men underwear
18           innerwear for man
19     men underwear pack of 3
Name: keyword, dtype: object

In [11]:
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")
chrome_options.add_argument("--disable-gpu")
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--disable-popup-blocking")
chrome_options.add_argument("--ignore-certificate-errors")
chrome_options.add_experimental_option("prefs", {
    "download.prompt_for_download": False,
    "download.directory_upgrade": True,
    "safebrowsing.enabled": True
})

# chrome_path = r"C:\Users\Rajashekar\Downloads\chromedriver-win64 (5)\chromedriver-win64\chromedriver.exe"

# browser = webdriver.Chrome(executable_path = chrome_path, chrome_options=chrome_options)

browser = webdriver.Chrome()
browser.maximize_window()
browser.get("https://www.amazon.in/dp/B0845FLB26/?th=1")
time.sleep(3)

In [12]:
scrapped_key = []
scrapped_title = []
scrapped_sponsored = []
scrapped_slot = []
scrapped_page = []
scrapped_url = []
scrapped_price=[]
brand_scrapped=[]

def get_url_keyword(keyword,page_num):
    url = f"https://www.amazon.in/s?k={keyword.lower().replace(' ','+')}&page={page_num}&ref=sr_pg_{page_num}"
    return url

url = "https://www.amazon.in"
time.sleep(3)

#try differnt code
try:
    browser.find_element(By.CSS_SELECTOR, "body > div > div.a-row.a-spacing-double-large > div.a-section > div > div > form > div.a-row.a-spacing-large > div > div > div.a-row.a-spacing-base > div > div.a-column.a-span6.a-span-last.a-text-right > a").click()
except:
    try:
        browser.find_element(By.CSS_SELECTOR, "body > div > div.a-row.a-spacing-double-large > div.a-section > div > div > form > div.a-row.a-spacing-large > div > div > div.a-row.a-spacing-base > div > div.a-column.a-span6.a-span-last.a-text-right").click()
    except:
        pass
time.sleep(3)

browser.get(url) 
time.sleep(3)

iteration = len(keyword_list)

for key in keyword_list:

    for page in range(1,2):

        browser.get(get_url_keyword(key,page))
        time.sleep(2)

        soup = BeautifulSoup(browser.page_source, "html.parser")
        
        table = soup.findAll("div",{"class","a-section a-spacing-base"})
        if len(table) == 0:
            table = soup.findAll("div",{"class","a-section a-spacing-base desktop-grid-content-view"})
        if len(table) == 0:
            table = soup.findAll("div",{"class","puis-card-container s-card-container s-overflow-hidden aok-relative puis-expand-height puis-include-content-margin puis puis-v19429uxcrjs2i2lzfaiol3kbc9 s-latency-cf-section puis-card-border"})
        print('len of table',len(table))
        
        for index, value in enumerate(table):
            try:
                brand_span = value.find("span", {"class": "a-size-base-plus a-color-base"})
                brand = brand_span.text.strip() if brand_span else ""
            except:
                brand = 'None'

            try:                                
                title_h2 = value.find("h2", {"class": "a-size-base-plus a-spacing-none a-color-base a-text-normal"})
                title1 = title_h2.text.strip() if title_h2 else ""
            except:
                try:                                
                    title_h2 = value.find("h2", {"class": "a-size-medium a-spacing-none a-color-base a-text-normal"})
                    title1 = title_h2.text.strip() if title_h2 else ""
                except:
                    title1 = 'None'

            # Final combined title
            full_title = f"{brand} {title1}".strip()

            try:
                is_sponsored = value.find("span", {"class": "puis-label-popover-default"}).text
            except:
                try:
                    is_sponsored = value.find("span", {"class": "puis-label-popover-default"}).text
                except:
                    is_sponsored = "Organic"

            try:
                url = value.find('a', {"class": "a-link-normal s-line-clamp-2 s-line-clamp-3-for-col-12 s-link-style a-text-normal"}).get('href')
                url = "https://www.amazon.in" + url
            except:                                 
                try:                                  
                    url = value.find('a', {"class": "a-link-normal s-line-clamp-3 s-link-style a-text-normal"}).get('href')
                    url = "https://www.amazon.in" + url
                except:
                    try:                                  
                        url = value.find('a', {"class": "a-link-normal s-line-clamp-4 s-link-style a-text-normal"}).get('href')
                        url = "https://www.amazon.in" + url
                    except:
                        url = ""
                

            try:
                price = value.find("span", {"class": "a-price-whole"}).text
            except:
                try:
                    price = value.find("span", {"class": "a-offscreen"}).text
                except:
                    price = "0"

            slot = index + 1

            # Append to lists
            scrapped_key.append(key)
            scrapped_title.append(full_title)
            scrapped_sponsored.append(is_sponsored)
            scrapped_slot.append(slot)
            scrapped_page.append(page)
            scrapped_url.append(url)
            scrapped_price.append(price)
            brand_scrapped.append(brand)
        
    print("Remaining",iteration)
    iteration = iteration - 1

len of table 48
Remaining 20
len of table 48
Remaining 19
len of table 73
Remaining 18
len of table 73
Remaining 17
len of table 48
Remaining 16
len of table 56
Remaining 15
len of table 53
Remaining 14
len of table 53
Remaining 13
len of table 70
Remaining 12
len of table 48
Remaining 11
len of table 48
Remaining 10
len of table 53
Remaining 9
len of table 65
Remaining 8
len of table 48
Remaining 7
len of table 70
Remaining 6
len of table 70
Remaining 5
len of table 70
Remaining 4
len of table 70
Remaining 3
len of table 48
Remaining 2
len of table 70
Remaining 1

In [13]:
data = pd.DataFrame(list(zip(scrapped_key,scrapped_title,scrapped_sponsored,scrapped_slot,scrapped_page,scrapped_url,scrapped_price,brand_scrapped)),
                    columns=['keyword','title','is_sponsored','slot','Page Result','url','price','brand'])

data['date'] = date.today()

data_g = data[['keyword', 'title', 'is_sponsored', 'slot', 'Page Result','date','url','price','brand']]
# data_g.sample(3)

In [14]:
data_g['is_sponsored'].value_counts()

is_sponsored
Organic      1074
Sponsored     108
Name: count, dtype: int64

In [15]:
                #############################-------amazon_sov-------##############################    
    
data_g = data_g[['date', 'keyword', 'title', 'is_sponsored', 'price','slot', 'Page Result','url','brand']]

data_g['title'] = data_g['title'].apply(lambda x:x.strip())
data_g['keyword'] = data_g['keyword'].apply(lambda x:x.strip())
data_g['is_sponsored'] = data_g['is_sponsored'].apply(lambda x:x.strip())

data_gg = data_g.rename(columns = {
                           'keyword':'keyword',
                           'title':'title',
                           'is_sponsored':'is_sponsored',
                           'slot':'slot',
                           'Page Result':'page_result'})

data_gg['asin'] = data_gg['url'].apply(lambda x: x.split("dp%2F")[1].split("%2F")[0]
                                               if "dp%2F" in x
                                               else x.split("dp/")[1].split("/ref")[0]
                                               if "dp/" in x
                                               else x )

data_gg = data_gg.sort_values(['date']).reset_index(drop=True)
data_gg['date'] = pd.to_datetime(data_gg['date']).dt.date
data_gg['hour'] = datetime.today().strftime('%H')

data_gg.sample(3)

,date,keyword,title,is_sponsored,price,slot,page_result,url,brand,asin,hour
1160,2025-09-01,jockey underwear for men,Jockey IC24 Men's Tencel Micro Modal Cotton El...,Organic,399,26,1,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...,Jockey,B01H5FX64O,17
1158,2025-09-01,jockey underwear for men,Jockey IC24 Men's Tencel Micro Modal Cotton El...,Organic,399,28,1,https://www.amazon.in/Jockey-Mens-Solid-Brief-...,Jockey,B07R9LVSLL,17
1090,2025-09-01,jockey trunk for men,Jockey FP03 Men's Super Combed Cotton Rib Soli...,Organic,309,25,1,https://www.amazon.in/Jockey-Combed-Cotton-Ult...,Jockey,B0BP12YY5D,17

In [27]:
df=asins_sheet[['category','sub_category','keyword','account','BCG']]
df.head(2)

  category sub_category                  keyword account    BCG
0      MIW       Trunks    jockey under wear men  Jockey  Brand
1      MIW       Trunks  jokey underwear for men  Jockey  Brand

In [28]:
final_df=pd.merge(data_gg,df,on='keyword',how='left')

In [29]:
final_df.columns

Index(['date', 'keyword', 'title', 'is_sponsored', 'price', 'slot',
       'page_result', 'url', 'brand', 'asin', 'hour', 'category',
       'sub_category', 'account', 'BCG'],
      dtype='object')

In [30]:
final_df=final_df[['date', 'keyword', 'title', 'is_sponsored', 'price', 'slot',
       'page_result', 'asin', 'hour', 'account',  'brand','category',
       'sub_category',  'BCG']]

In [ ]:
final_df.to_clipboard(index =0)

In [37]:
import psycopg2
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://postgres:tr0ub4dor&3@nucleus.ckojnefw0d56.us-west-1.rds.amazonaws.com/GIF_2025')

final_df.to_sql('amazon_sov', engine, if_exists='append', index=False)

182

In [ ]:
browser.quit()

In [31]:
final_df.head(10)

,date,keyword,title,is_sponsored,price,slot,page_result,asin,hour,account,brand,category,sub_category,BCG
0,2025-09-01,jockey under wear men,Jockey 8009 Men's Super Combed Cotton Rib Soli...,Organic,847,1,1,B0CJFTD6HQ,17,Jockey,Jockey,MIW,Trunks,Brand
1,2025-09-01,underwear,XYXX Men's Dualist Micromodal Regular Fit Colo...,Organic,999,8,1,B07XYV9DXG,17,Jockey,XYXX,MIW,Trunks,Generic
2,2025-09-01,underwear,Van Heusen Men Boxer Briefs - 100% Combed Cott...,Organic,470,7,1,B073WCC5YL,17,Jockey,Van Heusen,MIW,Trunks,Generic
3,2025-09-01,underwear,Jockey 8037 Men's Super Combed Cotton Solid Br...,Organic,378,6,1,B014213BHG,17,Jockey,Jockey,MIW,Trunks,Generic
4,2025-09-01,underwear,Jockey 8009 Men's Super Combed Cotton Rib Soli...,Organic,829,5,1,B0CJFS3FW9,17,Jockey,Jockey,MIW,Trunks,Generic
5,2025-09-01,underwear,Jockey NY16 Men's Super Combed Cotton Elastane...,Sponsored,679,4,1,B0C3MBVFHJ,17,Jockey,Jockey,MIW,Trunks,Generic
6,2025-09-01,underwear,XYXX Men's Uno Micromodal Regular Fit Solid An...,Sponsored,499,3,1,B08V59DCL8,17,Jockey,XYXX,MIW,Trunks,Generic
7,2025-09-01,underwear,XYXX Men's Modal Relaxed Printed Trunks,Organic,550,9,1,B07XYRMTXF,17,Jockey,XYXX,MIW,Trunks,Generic
8,2025-09-01,underwear,Jockey 8009 Men's Super Combed Cotton Rib Soli...,Sponsored,569,2,1,B01420KN9G,17,Jockey,Jockey,MIW,Trunks,Generic
9,2025-09-01,inner for men,"DAMENSCH Neo-Skin Round Neck Vest, Anti-Bacter...",Organic,479,48,1,B0C1TMWJCF,17,Jockey,DAMENSCH,MIW,Trunks,Generic