In [3]:
from bs4 import BeautifulSoup
from datetime import timedelta
from datetime import datetime
from requests.auth import HTTPBasicAuth
import requests
import time
import re
import pandas as pd
from datetime import datetime
from datetime import date
from gspread_pandas import Spread,Client
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import Select
global driver
import warnings
warnings.filterwarnings("ignore")
my_credentials=my_credentials= {         
  "type": "service_account",
  "project_id": "crafty-plateau-328717",
  "private_key_id": "4afdb5a0906054d2d69cd46b2e8af41b73b9b8a7",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcQv0qyESqHiYz\n82V5rSDiEG8xMGF0hIC9cJirwrDgAhEpjKIQRnJ227g6CP/8CTYYSrvJXmGzTZrB\n+FtrYWeZPjuIZGPyPJShIG//4LWcjlnh/h5zilKcmyaKsu5M0BSWiW0rkIUwYFgS\nox6xfiW3UbYWIUAGVvwDBYopUExaEV/a9l8p43pKDXHmZfq4ZIu2XgLDqalDLbCW\n1FjU7umMWS9KEvibo6mUkia9kkw1DvEsIkbWny3Bm0SoDLeqG0B6OsXhOYMfEJ+W\nSR80TR4Fu+EVfzRocwNVQHOKB2o0mbd/0AA1z/OPGM99QJXXKm8+CdV0KTbj6MUB\ns2/YTlG5AgMBAAECggEAKJ8IHrhBhZg61nDogYiu3FJIl2tDReBb99QIrACjaySm\ncqG3j8XWPVpnPvjC8QHn4pIB0PDhltZUmLpLbeHQX+AszYoqLpYCmTaowSl5hO5x\n4C5kAk37z1sDwCegsDTd3ydoJVUpYxMZmxJPSk+n+AePS8SFEMZBAvOmF9lxw1hC\nJoYkw4/H9XvuW7fTiOK2le6GokWgDUqSgTQRHO78NION1Z5pB5ymAKrV7w5GH4LI\nkFIuOxQEHhLv0a2URVEzkHX3VGPbBHF4MQ/Z8ObxqEsefkOnEpRIRTsE8+G44coB\nYbVdhe0132qgotEN1GvsBLwq+TJIknt38jkDcs9sKwKBgQD+sGqDtvCzSz5rk/Xg\nNHFOq9FsWSeUuw9jxw4XJxVqYbJbLcy0DmfIPg1rZgPW8X+6upt5RigHVBixqz74\nsnP9IvmVuoU6s9VoW1HaYbnbg5Zqp3WFa6xHZv/vXIapfCX8binEsVWwYW2gb2AJ\nE13jFJWZB7n8zatEk9ho1Rv50wKBgQDdZTXjsc0N3DZhCR39zPGr811VBmnXuUwW\nG1MG7z4npe2eFeTYHepKN8c3Ot+boyDm+K+NsEYHLH6wlcXFxMHAgSY6xAe8k+4i\n8EgwgUPfmawUrv7tXsAhASZNJwoE4S9S/kY/WFJR6CddaMUYvNtle5P99D//uoGG\nXcJWdEsiwwKBgQDBNaoIM98T1RAMYlmTdZVDfjrIPDY3sVSyd85rp/2qD2VToEH7\nkjYPBWv+voxJIjmouWm6rYsuTBDTr7p8xjwRm9fFS5NIfiZ2HVjSF3L8YS3ZySHx\nTkaKgEvGFOYfawwSHKxZB8KepLqajANJv0RpQTNfvSnN62RzCMmSdaDcewKBgQC8\nKuprdNHYRuL9BDe2X7rDr5sSydmpnPa7D0w455wHLLLRmsAeowZfQBsUqPgmGra7\nOIBUx44tSLcAtLscBMe8KshoR/ZfY8eRcHGasDMU11J3XeiTrOVU59o61sRgM1f6\njNz9t753mP3kGUjzZoh+L1MwE6lVW5n8rrGes0as6wKBgE54ZYZcUXRbOh+d1I9e\njWfwqr/mfvVGUZIBP4qDgL4dNHPWzWT7gjZIQUWJyXIMjP+04dly5ugJIX5UEC1M\nWPH1f9nsW3tvSp5suycEvtyXqEqrudLTHPOKhFWFDdh1bpO6y6GuAXMBU7FywTgi\n49Cl8Nil36anL8yJHhf7RSOF\n-----END PRIVATE KEY-----\n",
  "client_email": "aakashgooglesheets@crafty-plateau-328717.iam.gserviceaccount.com",
  "client_id": "108448941747378112883",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/aakashgooglesheets%40crafty-plateau-328717.iam.gserviceaccount.com"
}

In [50]:
spread = Spread('GIF_2025_Mapping_Requirement',config=my_credentials) ## worksheet_name
sheet = spread.open_sheet("Flipkart_SOV")                                        ##sheet_name
asins_sheet = spread.sheet_to_df(sheet=sheet,index=0)
asins_sheet.head()

,keyword,account,category,sub_category,sub_category_1,sub_category_2,sub_category_3
0,underwear for men,Jockey,MIW,Boxer Briefs,,,
1,mens underwear in cotton,Jockey,MIW,Boxer Briefs,,,
2,underwear for men cotton,Jockey,MIW,Boxer Briefs,,,
3,cotton underwear for men,Jockey,MIW,Boxer Briefs,,,
4,briefs for men,Jockey,MIW,Boxer Briefs,,,

In [51]:
filtered_df = asins_sheet[['keyword','account',"sub_category","sub_category_1","sub_category_2","sub_category_3"]]

In [49]:
filtered_df

,keyword,account,sub_category,sub_category_1,sub_category_2,sub_category_3
0,underwear for men,Jockey,Boxer Briefs,,,
1,mens underwear in cotton,Jockey,Boxer Briefs,,,
2,underwear for men cotton,Jockey,Boxer Briefs,,,
3,cotton underwear for men,Jockey,Boxer Briefs,,,
4,briefs for men,Jockey,Boxer Briefs,,,
...,...,...,...,...,...,...
430,vest for boys,Jockey,Vests,,,
431,vest for kids,Jockey,Vests,,,
432,kids innerwear,Jockey,Vests,,,
433,baniyan for kids boys,Jockey,Vests,,,
434,baniyan,Jockey,Vests,,,

In [7]:
# First convert the zipped items to a list
zipped_items = list(zip(filtered_df['keyword'], filtered_df['account']))
sliced_items=zipped_items[0:10]
acc_kay = dict(sliced_items)

In [8]:
len(acc_kay)

10

In [9]:
len(zipped_items)

435

In [ ]:
# acc_kay=acc_kay[]               # Rohit
# acc_kay=acc_kay[]            # Ajay
# acc_kay=acc_kay[]           # koushik
# acc_kay=acc_kay[]          # surya
# acc_kay=acc_kay[]          # shruthi
# acc_kay=acc_kay[]          # jibin
# acc_kay=acc_kay[]          # karnakaran
# acc_kay=acc_kay[]              # Hemanth

In [23]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from bs4 import BeautifulSoup
import time

# --- Setup Variables ---
scrapped_key = []
scrapped_title = []
scrapped_sponsored = []
scrapped_slot = []
scrapped_page = []
brand = []
scrapped_FSN = []
scrap_price = []
account_name = []
scrapped_mrp=[]
scrapped_brand=[]

# Example acc_kay (replace this with your sliced dict)
# acc_kay = dict(zip(filtered_df['keyword'], filtered_df['account']))
# acc_kay = dict(list(zip(filtered_df['keyword'], filtered_df['account']))[1144:1248])
# Uncomment above line and use your actual `filtered_df`

def get_url_keyword(keyword, page_num):
    url = f"https://www.flipkart.com/search?q={keyword.lower().replace(' ','+')}&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page={page_num}"
    return url

# Setup ChromeDriver
# chrome_driver_path = r"C:\Users\Rajashekar\Downloads\chromedriver-win64 (5)\chromedriver-win64\chromedriver.exe"  # Change this to your path

options = Options()
options.add_argument("--start-maximized")
# service = Service(executable_path=chrome_driver_path)

# driver = webdriver.Chrome(service=service, options=options)
driver = webdriver.Chrome()
# Scraping starts
iteration = len(acc_kay)

for key, account in acc_kay.items():
    print("Keyword:", key)

    for page in range(1, 2):  # Change range for more pages
        driver.get(get_url_keyword(key, page))
        time.sleep(2)

        html = driver.page_source
        soup = BeautifulSoup(html, "html.parser")

        table = soup.findAll("div", {"class": "_1sdMkc LFEi7Z"})
        if not table:
            table = soup.findAll("div", {"class": "_75nlfW"})

        print("Products found:", len(table))

        for index, value in enumerate(table):
            # Title
            title_tag = value.find("a", {"class": "WKTcLC"}) or value.find("div", {"class": "KzDlHZ"})
            title = title_tag.text.strip() if title_tag else "N/A"
            brand_tag=value.find("div", {"class": "syl9yP"}) 
            brand = brand_tag.text.strip() if brand_tag else "N/A"
            # FSN
            fsn_tag = value.find("a", {"class": "rPDeLR"}) or value.find("a", {"class": "CGtC98"}) or value.find("a", {"class": "tUxRFH"})
            if fsn_tag and fsn_tag.get("href"):
                try:
                    FSN = fsn_tag.get("href").split("?pid=")[1].split("&")[0]
                except:
                    FSN = "N/A"
            else:
                FSN = "N/A"

            # Sponsored Check
            if value.find("div", {"class": "_2ABVdq"}) or value.find("div", {"class": "f8qK5m"}):
                is_sponsored = "Sponsored"
            else:
                is_sponsored = "Organic"

            # Price
            price_tag = value.find("div", {"class": "Nx9bqj"}) or value.find("div", {"class": "Nx9bqj _4b5DiR"})
            price = price_tag.text.replace("₹", "").strip() if price_tag else "0"
            mrp_tag = value.find("div", {"class": "yRaY8j"}) or value.find("div", {"class": "Nx9bqj _4b5DiR"})
            mrp = mrp_tag.text.replace("₹", "").strip() if mrp_tag else "0"
            # Slot
            slot = index + 1

            # Append to lists
            scrapped_key.append(key)
            scrapped_title.append(title)
            scrapped_sponsored.append(is_sponsored)
            scrapped_slot.append(slot)
            scrapped_page.append(page)
            scrapped_FSN.append(FSN)
            scrap_price.append(price)
            account_name.append(account)
            scrapped_mrp.append(mrp)
            scrapped_brand.append(brand)

    print("Remaining:", iteration - 1)
    iteration -= 1

# --- Done ---
driver.quit()

Keyword: underwear for men
Products found: 40
Remaining: 9
Keyword: mens underwear in cotton
Products found: 40
Remaining: 8
Keyword: underwear for men cotton
Products found: 40
Remaining: 7
Keyword: cotton underwear for men
Products found: 40
Remaining: 6
Keyword: briefs for men
Products found: 40
Remaining: 5
Keyword: sexy underwear for men
Products found: 40
Remaining: 4
Keyword: under garments for men
Products found: 40
Remaining: 3
Keyword: under garment mens
Products found: 40
Remaining: 2
Keyword: undergarments for men
Products found: 40
Remaining: 1
Keyword: inner for men
Products found: 40
Remaining: 0

In [24]:
flipkart_data=pd.DataFrame(list(zip(scrapped_key,scrapped_title,scrapped_sponsored,scrapped_slot,scrapped_page,scrapped_FSN,scrap_price,account_name,scrapped_mrp,scrapped_brand)),columns=['keyword','title',
                                                                                                  'is_sponsored','slot','page_result','fsn','price','account','mrp','brand'])

In [26]:
flipkart_data['title']=flipkart_data['brand']+" "+flipkart_data['title']

In [27]:
flipkart_data

,keyword,title,is_sponsored,slot,page_result,fsn,price,account,mrp,brand
0,underwear for men,jicks Pack of 4 Men Trunk,Sponsored,1,1,BRFHCSPWTXZN6A5U,348,Jockey,799,jicks
1,underwear for men,jicks Pack of 4 Printed Men Brief,Sponsored,2,1,BRFH2PGDW38FRK7Z,348,Jockey,999,jicks
2,underwear for men,Lorcan Pack of 3 Solid Men Trunk,Organic,3,1,BRFGSW84J6WCNSGR,220,Jockey,999,Lorcan
3,underwear for men,Ckcosmed Solid Men Brief,Organic,4,1,BRFHEJWTWB2QZJMJ,177,Jockey,499,Ckcosmed
4,underwear for men,XYXX Nova IntelliFresh Cotton Grey Solid Men B...,Sponsored,5,1,BRFHYAN3JJCVTNRH,189,Jockey,249,XYXX
...,...,...,...,...,...,...,...,...,...,...
395,inner for men,Intimantic Solid Men Brief,Organic,36,1,BRFHE5HMTM3MCYAT,301,Jockey,499,Intimantic
396,inner for men,XYXX Pack of 2 Underwear Uno Intellisoft Micro...,Sponsored,37,1,BRFGYCHKNKBFGRNC,499,Jockey,538,XYXX
397,inner for men,Dixcy Scott Josh Pack of 5 Solid Men Trunk,Sponsored,38,1,BRFHBZYCMVQU3DWW,375,Jockey,630,Dixcy Scott Josh
398,inner for men,VIP Pack of 4 Solid Men Brief,Organic,39,1,BRFGCQYVWKNVGATY,348,Jockey,480,VIP
399,inner for men,jicks Printed Men Trunk,Organic,40,1,BRFGYBHH9VFUHAGJ,99,Jockey,599,jicks

In [29]:
final_fk_sov=flipkart_data[['keyword','title','is_sponsored','slot','page_result','fsn','price','account','mrp','brand']]
final_fk_sov['date'] = date.today()
import pytz
tz = pytz.timezone('Asia/Kolkata')
col_name = datetime.now(tz=tz).strftime("%H")
final_fk_sov['hour']=col_name

In [30]:
final_fk_sov.head(2)

,keyword,title,is_sponsored,slot,page_result,fsn,price,account,mrp,brand,date,hour
0,underwear for men,jicks Pack of 4 Men Trunk,Sponsored,1,1,BRFHCSPWTXZN6A5U,348,Jockey,799,jicks,2025-09-02,16
1,underwear for men,jicks Pack of 4 Printed Men Brief,Sponsored,2,1,BRFH2PGDW38FRK7Z,348,Jockey,999,jicks,2025-09-02,16

In [38]:
final_fk_sov

,keyword,title,is_sponsored,slot,page_result,fsn,price,account,mrp,brand,date,hour
0,underwear for men,jicks Pack of 4 Men Trunk,Sponsored,1,1,BRFHCSPWTXZN6A5U,348,Jockey,799,jicks,2025-09-02,16
1,underwear for men,jicks Pack of 4 Printed Men Brief,Sponsored,2,1,BRFH2PGDW38FRK7Z,348,Jockey,999,jicks,2025-09-02,16
2,underwear for men,Lorcan Pack of 3 Solid Men Trunk,Organic,3,1,BRFGSW84J6WCNSGR,220,Jockey,999,Lorcan,2025-09-02,16
3,underwear for men,Ckcosmed Solid Men Brief,Organic,4,1,BRFHEJWTWB2QZJMJ,177,Jockey,499,Ckcosmed,2025-09-02,16
4,underwear for men,XYXX Nova IntelliFresh Cotton Grey Solid Men B...,Sponsored,5,1,BRFHYAN3JJCVTNRH,189,Jockey,249,XYXX,2025-09-02,16
...,...,...,...,...,...,...,...,...,...,...,...,...
395,inner for men,Intimantic Solid Men Brief,Organic,36,1,BRFHE5HMTM3MCYAT,301,Jockey,499,Intimantic,2025-09-02,16
396,inner for men,XYXX Pack of 2 Underwear Uno Intellisoft Micro...,Sponsored,37,1,BRFGYCHKNKBFGRNC,499,Jockey,538,XYXX,2025-09-02,16
397,inner for men,Dixcy Scott Josh Pack of 5 Solid Men Trunk,Sponsored,38,1,BRFHBZYCMVQU3DWW,375,Jockey,630,Dixcy Scott Josh,2025-09-02,16
398,inner for men,VIP Pack of 4 Solid Men Brief,Organic,39,1,BRFGCQYVWKNVGATY,348,Jockey,480,VIP,2025-09-02,16
399,inner for men,jicks Printed Men Trunk,Organic,40,1,BRFGYBHH9VFUHAGJ,99,Jockey,599,jicks,2025-09-02,16

In [52]:
final_df = pd.merge(final_fk_sov,filtered_df, on=['keyword', 'account'], how='left')

In [55]:
import psycopg2
from sqlalchemy import create_engine
engine = create_engine('postgresql+psycopg2://postgres:tr0ub4dor&3@nucleus.ckojnefw0d56.us-west-1.rds.amazonaws.com/GIF_2025')

final_df.to_sql('flipkart_sov', engine, if_exists='append', index=False)

600

In [54]:
final_df.columns

Index(['keyword', 'title', 'is_sponsored', 'slot', 'page_result', 'fsn',
       'price', 'account', 'mrp', 'brand', 'date', 'hour', 'sub_category',
       'sub_category_1', 'sub_category_2', 'sub_category_3'],
      dtype='object')

In [ ]:
driver.quit()